services:
  jenkins:
    build:
      context: .
      x-bake:
        cache-from:
          - type=gha
        cache-to:
          - type=gha,mode=max
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
