/**
 * Jenkins Script Console — export installed plugins as a Gradle version catalog.
 *
 * Run this in Manage Jenkins → Script Console on the Jenkins instance whose plugin
 * versions you want to pin in your shared library's test dependencies.
 *
 * The output is a valid `jenkins.versions.toml` file.  Save it to
 * `gradle/jenkins.versions.toml` in your shared library project and wire it in
 * `settings.gradle.kts`:
 *
 *   dependencyResolutionManagement {
 *     versionCatalogs {
 *       create("jenkinsPlugins") {
 *         from(files("gradle/jenkins.versions.toml"))
 *       }
 *     }
 *   }
 *
 * Then reference plugins by their short name as typed accessors:
 *
 *   jenkinsPlugin(jenkinsPlugins.workflow.job)
 *   jenkinsPlugin(jenkinsPlugins.pipeline.model.definition)
 *
 * Re-run and replace the file whenever plugins are upgraded on the instance.
 */

import hudson.PluginWrapper
import java.time.Instant

// Convert a plugin short name (kebab-case) to a TOML key (dots for nesting, safe characters).
// "workflow-job" → "workflow.job", "pipeline-model-api" → "pipeline.model.api"
String tomlKey(String shortName) {
  shortName.replaceAll('-', '.')
}

final List<Map<String, String>> plugins = Jenkins.instance.pluginManager.plugins
  .findAll { PluginWrapper p -> p.active && !p.deleted }
  .collect { PluginWrapper p ->
    [
      groupId: p.manifest.mainAttributes.getValue('Group-Id') ?: 'unknown',
      shortName: p.shortName,
      version: p.version,
    ]
  }
  .sort { Map<String, String> p -> p.shortName }

final String versions = plugins
  .collect { Map<String, String> p -> "${tomlKey(p.shortName)} = \"${p.version}\"" }
  .join('\n')

final String libraries = plugins
  .collect { Map<String, String> p ->
    p.groupId == 'unknown'
      ? "# WARNING: no Group-Id in manifest for ${p.shortName} — add group manually\n" +
        "# ${tomlKey(p.shortName)} = { module = \"?:${p.shortName}\", version.ref = \"${tomlKey(p.shortName)}\" }"
      : "${tomlKey(p.shortName)} = { module = \"${p.groupId}:${p.shortName}\", version.ref = \"${tomlKey(p.shortName)}\" }"
  }
  .join('\n')

// Only include plugins with a known group in the bundle (unknown-group entries are comments).
final String bundleEntries = plugins
  .findAll { Map<String, String> p -> p.groupId != 'unknown' }
  .collect { Map<String, String> p -> "    \"${tomlKey(p.shortName)}\"" }
  .join(',\n')

print """\
# Generated by scripts/export-jenkins-catalog.groovy
# Source: ${Jenkins.instance.rootUrl ?: 'unknown'}
# Jenkins: ${Jenkins.VERSION}
# Date: ${Instant.now()}

[versions]
${versions}

[libraries]
${libraries}

[bundles]
all-plugins = [
${bundleEntries},
]
"""
