name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE.txt'
      - '.gitignore'
      - 'local-jenkins/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE.txt'
      - '.gitignore'
      - 'local-jenkins/**'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    env:
      DEVELOCITY_PUBLISH: "1"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287
        with:
          java-version: 21
          distribution: temurin
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
      - name: Build
        run: ./gradlew build --continue
